name: Aggiorna Dati
on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * *' 

# Forza l'uso di Node.js 24 per compatibilità con i nuovi runner 2026
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4 # Versione aggiornata
        
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: 'IL_TUO_LINK_CSV_DI_GOOGLE'
          downloaded_filename: campane.csv
