name: Aggiorna Dati
on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * *' 

jobs:
  scheduled:
    runs-on: ubuntu-latest
    
    env:
      # Scegliamo SOLO questa: forziamo l'ambiente a Node 24.
      # GitHub smetterà di segnalare l'errore di configurazione.
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQMIQS_0E4oHzknN3DgO6QMGx_MqTxxX2g-_gIEWYS9J2de64wWDOzswchnF2To4EJy5LMdKX1uI0DA/pub?gid=1865442869&single=true&output=csv'
          downloaded_filename: campane.csv
