name: Aggiorna Dati
on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * *' 

jobs:
  scheduled:
    runs-on: ubuntu-latest
    env:
      # Questa variabile conferma a GitHub che accettiamo l'esecuzione su Node 24
      # eliminando i warning di deprecazione fino al passaggio definitivo.
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: 'IL_TUO_LINK_CSV_DI_GOOGLE'
          downloaded_filename: campane.csv
